name: krom-test-be

services:
  app:
    container_name: krom-test-be-app
    build:
      context: .
      dockerfile: Dockerfile
    image: krom-test-be
    ports:
      - '6001:6001'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:P@55w0rd@krom-test-be-mysql:3306/krom-test
    depends_on:
      mysql:
        condition: service_healthy
      migration-and-seed:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - krom-test-network

  mysql:
    image: mysql:8.0
    container_name: krom-test-be-mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@55w0rd
      MYSQL_DATABASE: krom-test
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - ':3306'
    networks:
      - krom-test-network

  migration-and-seed:
    command: sh -c "npm run migrate-production && npm run seed-production"
    image: krom-test-be
    container_name: krom-test-be-migrate-and-seed
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:P@55w0rd@krom-test-be-mysql:3306/krom-test
    networks:
      - krom-test-network
    restart: 'no'

networks:
  krom-test-network:
    driver: bridge
